[package]
name = "chrome-devtools-rs"
version = "0.1.0"
authors = ["Avery Harnish <averyharnish@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
serde = "1.0.103"
serde_derive = "1.0.103"
serde_with = "1.3.1"

[lib]
name = "chrome_devtools"
path = "src/lib.rs"
